modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL = "https://github.com/AbbyGrail/CrudeRust/issues"
license="All Rights Reserved"

[[mods]]
modId="cruderust"
version="1.21.1-0.1"
displayName="CrudeRust"
displayURL="https://github.com/AbbyGrail/CrudeRust"
#logoFile="examplemod.png" #remember to add this later on
credits="AbbyGrail"
authors="AbbyGrail"
description="Alternative take on minecraft's progression"
#[[mixins]]
#config="cruderust.mixins.json" #keeping this for later

[[dependencies.cruderust]]
    modId="neoforge"
    type="required"
    versionRange="21.1.77"
    ordering="NONE"
    side="BOTH"

[[dependencies.cruderust]]
    modId="minecraft"
    type="required"
    versionRange="1.21.1"
    ordering="NONE"
    side="BOTH"
